### ISSUE TITLE
Create new resource regards http 201 as an error

### ISSUE THREAD

**Issue by andersbetner** [360youlun/targetprocess-client#3]
If I create a new resource the API responds with http 201 Created, but the targetprocess-client only accepts http 200 as a valid answer.

``` python
from targetprocess.api import TargetProcessAPIClient

tp = TargetProcessAPIClient(
    api_url='https://md5.tpondemand.com/api/v1/',
    user=USER,
    password=PW)
tp.update_resource(collection="Tasks", entity_id=None, data={'Name': 'New task I think', 'UserStory': {'Id': 1234}})
```

```
Traceback (most recent call last):
  File "tp_add.py", line 7, in <module>
    tp.update_resource(collection="Tasks", entity_id=None, data={'Name': 'New task I think', 'UserStory': {'Id': 1234}})
  File "/usr/local/src/brp/targetprocess/targetprocess/api.py", line 107, in update_resource
    return self._post(url, data)
  File "/usr/local/src/brp/targetprocess/targetprocess/api.py", line 168, in _post
    return self._do_request(method='post', url=url, data=json_data, headers=headers)
  File "/usr/local/src/brp/targetprocess/targetprocess/api.py", line 176, in _do_request
    raise BadResponseError(response=response)
targetprocess.exceptions.BadResponseError: Status Code 201
Content:
b'{"ResourceType":"Task","Id":1235}'
```

**Comment by magicjohnson** [comment]
fixed
